apiVersion: apps/v1
kind: Deployment

metadata:
  name: django-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: django-app

  template:
    metadata:
      labels:
        app: django-app

    spec:
      containers:
        - name: django-app

          image: jibin321/ultimate-cicd:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"