apiVersion: apps/v1
kind: Deployment

metadata:
  name: django-app
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: django-app

  template:
    metadata:
      labels:
        app: django-app

    spec:
      containers:
        - name: django-app
          image: jibin321/django-app:f4d13f044db2e1aafd9bd8e6e09f18dd52dbfb34

          ports:
            - containerPort: 8000
