pipeline {
    agent {
        docker {
            image 'python:3.11-slim'
            args '--user root'
        }
    }

    environment {
        SONAR_HOST_URL = 'http://YOUR-EC2-IP:9000'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
                sh 'echo Checkout completed successfully'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                  pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest pytest-django pytest-cov
                '''
            }
        }

        stage('Build and Test') {
            steps {
                dir('test_django_pro') {
                    sh '''
                      python manage.py makemigrations --check --dry-run
                      python manage.py migrate

                      pytest todos/tests.py \
                        --ds=test_django_pro.settings
                        --junitxml=report.xml \
                        --cov=todos \
                        --cov-report=xml
                    '''
                }
            }

            post {
                always {
                    junit 'test_django_pro/report.xml'
                }
            }
        }

        stage('Static Code Analysis') {
            steps {
                sh '''
                  sonar-scanner \
                    -Dsonar.projectKey=django-app \
                    -Dsonar.sources=. \
                    -Dsonar.host.url=$SONAR_HOST_URL \
                    -Dsonar.login=admin \
                    -Dsonar.password=admin
                '''
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                sh '''
                  docker build -t django-app .
                '''
            }
        }

        stage('Update Deployment File') {
            steps {
                sh 'echo Deployment update stage completed'
            }
        }
    }

    post {
        always {
            cleanWs()
        }

        success {
            echo 'Pipeline executed successfully!'
        }

        failure {
            echo 'Pipeline failed! Check logs above.'
        }
    }
}
