pipeline {
    agent {
        docker {
            image 'python:3.11-slim'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        SONAR_HOST_URL = 'http://32.236.85.107:9000'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
                sh 'echo Checkout completed successfully'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    apt-get update
                    apt-get install -y docker.io

                    pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install pytest pytest-django pytest-cov
                '''
            }
        }

        stage('Build and Test') {
            steps {
                dir('test_django_pro') {
                    sh '''
                        python manage.py makemigrations --check --dry-run
                        python manage.py migrate

                        pytest \
                          --ds=test_django_pro.settings \
                          --junitxml=report.xml \
                          --cov=. \
                          --cov-report=xml || true
                    '''
                }
            }

            post {
                always {
                    junit allowEmptyResults: true, testResults: 'test_django_pro/report.xml'
                }
            }
        }

        stage('Static Code Analysis') {
            steps {
                sh '''
                    docker run --rm \
                      -e SONAR_HOST_URL=$SONAR_HOST_URL \
                      sonarsource/sonar-scanner-cli \
                      -Dsonar.projectKey=django-app \
                      -Dsonar.sources=. \
                      -Dsonar.host.url=$SONAR_HOST_URL \
                      -Dsonar.token=squ_64c181120ef2253a30328920e42c73c47173c732
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build -t django-app .
                '''
            }
        }

        stage('Update Deployment File') {
            steps {
                sh 'echo Deployment update stage completed'
            }
        }
    }

    post {
        always {
            cleanWs()
        }

        success {
            echo 'Pipeline executed successfully!'
        }

        failure {
            echo 'Pipeline failed! Check logs above.'
        }
    }
}
